'use client';
import Image from 'next/image';
import { useState } from 'react';

export default function Portfolio() {
  const [selectedCategory, setSelectedCategory] = useState<string>('all');

  return (
    <div className="min-h-screen flex flex-col">
      <main className="flex-grow mt-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
          {/* Hero Section */}
          <div className="text-center mb-16">
            <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-4">
              AI Emoji Portfolio
            </h1>
            <p className="text-xl text-gray-600 dark:text-gray-300">
              Explore our collection of AI-generated emojis and creative projects
            </p>
          </div>

          {/* Filter Categories */}
          <div className="flex flex-wrap justify-center gap-4 mb-12">
            <FilterButton
              active={selectedCategory === 'all'}
              onClick={() => setSelectedCategory('all')}
            >
              All Projects
            </FilterButton>
            <FilterButton
              active={selectedCategory === 'emojis'}
              onClick={() => setSelectedCategory('emojis')}
            >
              Emojis
            </FilterButton>
            <FilterButton
              active={selectedCategory === 'stickers'}
              onClick={() => setSelectedCategory('stickers')}
            >
              Sticker Packs
            </FilterButton>
            <FilterButton
              active={selectedCategory === 'animations'}
              onClick={() => setSelectedCategory('animations')}
            >
              Animations
            </FilterButton>
          </div>

          {/* Featured Projects Grid */}
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8 mb-16">
            <ProjectCard
              title="Emoji Expression Pack"
              description="A collection of 50+ emotional expressions generated using our AI technology."
              image="/portfolio/emoji-pack.png"
              category="emojis"
              link="/"
              stats={{
                downloads: "2.5k",
                likes: "1.2k",
                views: "10k"
              }}
            />
            <ProjectCard
              title="Animal Emoji Series"
              description="Cute and expressive animal emojis created with advanced AI algorithms."
              image="/portfolio/animal-emojis.png"
              category="emojis"
              link="/"
              stats={{
                downloads: "1.8k",
                likes: "950",
                views: "8k"
              }}
            />
            <ProjectCard
              title="Food Sticker Collection"
              description="Delicious-looking food stickers generated by our AI system."
              image="/portfolio/food-stickers.png"
              category="stickers"
              link="/"
              stats={{
                downloads: "3.2k",
                likes: "1.5k",
                views: "12k"
              }}
            />
          </div>

          {/* Statistics Section */}
          <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-xl p-8 mb-16">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
              <StatCard
                number="10k+"
                label="Emojis Generated"
                icon={
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                }
              />
              <StatCard
                number="5k+"
                label="Happy Users"
                icon={
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                  </svg>
                }
              />
              <StatCard
                number="50+"
                label="Custom Packs"
                icon={
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
                  </svg>
                }
              />
              <StatCard
                number="4.9"
                label="Average Rating"
                icon={
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
                  </svg>
                }
              />
            </div>
          </div>

          {/* Testimonials */}
          <div className="space-y-8">
            <h2 className="text-3xl font-bold text-center text-gray-900 dark:text-white mb-8">
              What Our Users Say
            </h2>
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
              <TestimonialCard
                quote="The AI emoji generator has revolutionized how we create custom emojis for our platform."
                author="Sarah Johnson"
                role="Product Designer"
                image="/testimonials/user1.jpg"
              />
              <TestimonialCard
                quote="Incredibly intuitive and the results are amazing. This is the future of emoji creation!"
                author="Mike Chen"
                role="Content Creator"
                image="/testimonials/user2.jpg"
              />
              <TestimonialCard
                quote="The variety and quality of emojis we can generate is outstanding. Highly recommended!"
                author="Emma Davis"
                role="Social Media Manager"
                image="/testimonials/user3.jpg"
              />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

function FilterButton({ 
  children, 
  active, 
  onClick 
}: { 
  children: React.ReactNode; 
  active: boolean; 
  onClick: () => void; 
}) {
  return (
    <button
      onClick={onClick}
      className={`px-6 py-2 rounded-full text-sm font-medium transition-colors ${
        active 
          ? 'bg-blue-600 text-white' 
          : 'bg-gray-100 text-gray-600 hover:bg-gray-200 dark:bg-gray-700 dark:text-gray-300 dark:hover:bg-gray-600'
      }`}
    >
      {children}
    </button>
  );
}

function ProjectCard({ 
  title, 
  description, 
  image, 
  category, 
  link,
  stats 
}: { 
  title: string; 
  description: string; 
  image: string; 
  category: string;
  link: string;
  stats: {
    downloads: string;
    likes: string;
    views: string;
  };
}) {
  return (
    <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm hover:shadow-md transition-shadow overflow-hidden">
      <div className="relative h-48">
        <Image
          src={image}
          alt={title}
          fill
          className="object-cover"
        />
      </div>
      <div className="p-6">
        <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-2">{title}</h3>
        <p className="text-gray-600 dark:text-gray-300 mb-4">{description}</p>
        <div className="flex justify-between text-sm text-gray-500 dark:text-gray-400 mb-4">
          <span>👥 {stats.views}</span>
          <span>❤️ {stats.likes}</span>
          <span>⬇️ {stats.downloads}</span>
        </div>
        <a
          href={link}
          className="inline-block w-full text-center bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded-lg transition-colors"
        >
          View Project
        </a>
      </div>
    </div>
  );
}

function StatCard({ 
  number, 
  label, 
  icon 
}: { 
  number: string; 
  label: string; 
  icon: React.ReactNode; 
}) {
  return (
    <div className="text-center">
      <div className="inline-flex items-center justify-center w-12 h-12 bg-blue-100 dark:bg-blue-900 text-blue-600 dark:text-blue-300 rounded-full mb-4">
        {icon}
      </div>
      <div className="text-2xl font-bold text-gray-900 dark:text-white mb-1">{number}</div>
      <div className="text-sm text-gray-500 dark:text-gray-400">{label}</div>
    </div>
  );
}

function TestimonialCard({ 
  quote, 
  author, 
  role, 
  image 
}: { 
  quote: string; 
  author: string; 
  role: string; 
  image: string; 
}) {
  return (
    <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm p-6">
      <div className="flex items-start mb-4">
        <div className="relative w-12 h-12 mr-4">
          <Image
            src={image}
            alt={author}
            fill
            className="rounded-full object-cover"
          />
        </div>
        <div>
          <div className="font-medium text-gray-900 dark:text-white">{author}</div>
          <div className="text-sm text-gray-500 dark:text-gray-400">{role}</div>
        </div>
      </div>
      <p className="text-gray-600 dark:text-gray-300 italic">"{quote}"</p>
    </div>
  );
} 